### ISSUE TITLE
quota limit error

### ISSUE THREAD

**Issue by bartekpacia** [wilsonwu/translation-google#5]
Hello

The library was working fine, but then ...it stopped. I didn't do anything. That's the error I was getting :
<img width="1070" alt="302" src="https://user-images.githubusercontent.com/40357511/79148847-7f3e3000-7dc6-11ea-8859-1222ea35eab8.png"> 

I decide to open the file where the error originated from (`node_modules/got/index.js:123:13`) and saw this code:
<img width="671" alt="got1" src="https://user-images.githubusercontent.com/40357511/79150596-58cdc400-7dc9-11ea-9589-430b26183093.png">

The HTTP response code was `302`, so I altered it this way:
<img width="720" alt="got3" src="https://user-images.githubusercontent.com/40357511/79150830-b235f300-7dc9-11ea-86a2-f47c7b84d4b9.png">

Then I executed the code again. That's the output:
<img width="1083" alt="got4" src="https://user-images.githubusercontent.com/40357511/79150889-d0035800-7dc9-11ea-9b8d-0920bcec78ca.png">

I clicked on that long link and the following page opened:
<img width="821" alt="sad" src="https://user-images.githubusercontent.com/40357511/79150932-e3aebe80-7dc9-11ea-9012-606d38281cef.png">

It looks like I hit the quota limit. I think that README.md should clearly inform about this and the library should handle such situation gracefully.

**Comment by wilsonwu** [comment]
Thank you for report this, I have not meet this yet, I think because this translate API is not the Google offical API, so there are some limit by Google, I will note this in README.md file soon, and so sorry for this.
