### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by Sannen147** [wilsonwu/translation-google#6]
Worked perfectly for a few hours, tried it again to test some things and it only shows "undefined" in console every time i try to translate something, is it my problem or the API's problem?

**Comment by Sannen147** [comment]
ok now it works again, probably because of google limit quota?

**Comment by wilsonwu** [comment]
Yes, you are right, Google has limitation for this way of usage for its translate service.
For commercial usage, suggest to pay for a translation service.
