### ISSUE TITLE
How long it will took when my IP getting banned?

### ISSUE THREAD

**Issue by 0wx** [wilsonwu/translation-google#7]
I run a bot to translate using your module, when it reach about 100 translate in a row, the google translate ban my server IP address. How long does it tooks for google realese IP ban?

**Comment by wilsonwu** [comment]
Thanks for submit this issue, I am not sure how long time it will ban, but I will write a warning in the readme of this project to let all know this risk.

**Comment by 0wx** [comment]
Thanks for answering @wilsonwu
Ok I understand, I'll close this issue since it's restrictions from google it self.

**Comment by wilsonwu** [comment]
@0wx no problem.
